
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 09 15:11:29 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 49;
  public static final int LEFT_BRACKETS = 42;
  public static final int CONST = 7;
  public static final int NOT_EQUAL = 27;
  public static final int GREATER = 29;
  public static final int CONTINUE = 17;
  public static final int NUM_CONST = 47;
  public static final int LESS = 31;
  public static final int MINUS = 22;
  public static final int LEFT_PARENTHESES = 40;
  public static final int LEFT_BRACES = 44;
  public static final int SEMICOLON = 36;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int COMMA = 38;
  public static final int CLASS = 4;
  public static final int INC = 19;
  public static final int DIV = 24;
  public static final int LESS_EQUAL = 30;
  public static final int PLUS = 21;
  public static final int ASSIGN = 35;
  public static final int IF = 8;
  public static final int RIGHT_BRACES = 45;
  public static final int DOT = 39;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int EQUAL = 26;
  public static final int GREATER_EQUAL = 28;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 23;
  public static final int MOD = 25;
  public static final int BREAK = 3;
  public static final int VOID = 15;
  public static final int RIGHT_BRACKETS = 43;
  public static final int ARROW = 34;
  public static final int COLON = 37;
  public static final int FOREACH = 18;
  public static final int RIGHT_PARENTHESES = 41;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int WHILE = 10;
  public static final int EXTENDS = 16;
  public static final int BOOL_CONST = 48;
  public static final int DEC = 20;
  public static final int PRINT = 12;
  public static final int DO = 9;
  public static final int IDENTIFIER = 46;
}

